#pragma once
#include "coagentics/market/Market.hpp"
#include <memory>
#include <random>
#include <string>
namespace coagentics::agents {
struct Observation { std::uint64_t time{}; std::string asset; double fundamental{}; double public_signal{}; double best_bid{}; double best_ask{}; double last_trade{}; };
class AgentPolicy { public: virtual ~AgentPolicy()=default; virtual std::string id() const=0; virtual coagentics::market::Bid act(const Observation&)=0; };
class HeuristicAgent : public AgentPolicy { public: HeuristicAgent(std::string id,double reservation,coagentics::market::Side side=coagentics::market::Side::Buy,int qty=1,double shade=0.05):id_(std::move(id)),reservation_(reservation),side_(side),qty_(qty),shade_(shade){} std::string id()const override{return id_;} coagentics::market::Bid act(const Observation&)override; protected: std::string id_; double reservation_; coagentics::market::Side side_; int qty_; double shade_; };
class ZeroIntelligenceAgent final : public AgentPolicy { public: ZeroIntelligenceAgent(std::string id,double reservation,coagentics::market::Side side,std::uint64_t seed,int qty=1,double span=40.0):id_(std::move(id)),reservation_(reservation),side_(side),rng_(seed),qty_(qty),span_(span){} std::string id()const override{return id_;} coagentics::market::Bid act(const Observation&)override; private: std::string id_; double reservation_; coagentics::market::Side side_; std::mt19937_64 rng_; int qty_; double span_; };
// Known-mechanism controls for benchmark recovery.
class InformationBlindAgent final : public AgentPolicy { public: InformationBlindAgent(std::string id,double reservation,coagentics::market::Side side):id_(std::move(id)),reservation_(reservation),side_(side){} std::string id()const override{return id_;} coagentics::market::Bid act(const Observation&o)override{return{o.time,id_,o.asset,1,reservation_,side_};} private:std::string id_;double reservation_;coagentics::market::Side side_;};
class SignalResponsiveAgent final : public AgentPolicy { public: SignalResponsiveAgent(std::string id,double reservation,coagentics::market::Side side,double gain=1.0):id_(std::move(id)),reservation_(reservation),side_(side),gain_(gain){} std::string id()const override{return id_;} coagentics::market::Bid act(const Observation&)override; private:std::string id_;double reservation_;coagentics::market::Side side_;double gain_;};
class RiskSensitiveAgent final : public AgentPolicy { public: RiskSensitiveAgent(std::string id,double reservation,coagentics::market::Side side,double aversion=.25):id_(std::move(id)),reservation_(reservation),side_(side),aversion_(aversion){} std::string id()const override{return id_;} coagentics::market::Bid act(const Observation&)override; private:std::string id_;double reservation_;coagentics::market::Side side_;double aversion_;};
class PeerResponsiveAgent final : public AgentPolicy { public: PeerResponsiveAgent(std::string id,double reservation,coagentics::market::Side side,double peer_gain=.6):id_(std::move(id)),reservation_(reservation),side_(side),peer_gain_(peer_gain){} std::string id()const override{return id_;} coagentics::market::Bid act(const Observation&)override; private:std::string id_;double reservation_;coagentics::market::Side side_;double peer_gain_;};
class AdaptiveAgent final : public AgentPolicy { public: AdaptiveAgent(std::string id,double reservation,coagentics::market::Side side,double learning=.2):id_(std::move(id)),reservation_(reservation),side_(side),learning_(learning){} std::string id()const override{return id_;} coagentics::market::Bid act(const Observation&)override; private:std::string id_;double reservation_;coagentics::market::Side side_;double learning_;double belief_{0};};
class LlmBidProvider { public: virtual ~LlmBidProvider()=default; virtual coagentics::market::Bid request_bid(const std::string& agent_id,const Observation&)=0; };
class LlmAgent final : public AgentPolicy { public:LlmAgent(std::string id,std::shared_ptr<LlmBidProvider> p):id_(std::move(id)),provider_(std::move(p)){}std::string id()const override{return id_;}coagentics::market::Bid act(const Observation&o)override{return provider_->request_bid(id_,o);}private:std::string id_;std::shared_ptr<LlmBidProvider> provider_;};
struct PopulationMember { std::string id; std::unique_ptr<AgentPolicy> policy; };
}
