#include "coagentics/experiment/ExperimentManifest.hpp"
#include <array>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>
namespace coagentics::experiment { namespace {
std::string esc(const std::string&s){std::string o;for(unsigned char c:s){switch(c){case '"':o+="\\\"";break;case '\\':o+="\\\\";break;case '\n':o+="\\n";break;case '\r':o+="\\r";break;case '\t':o+="\\t";break;default:if(c<0x20){std::ostringstream x;x<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<(int)c;o+=x.str();}else o+=(char)c;}}return o;}
void strings(std::ostringstream&o,const std::vector<std::string>&v){o<<"[";for(size_t i=0;i<v.size();++i){if(i)o<<",";o<<"\""<<esc(v[i])<<"\"";}o<<"]";}
constexpr std::array<std::uint32_t,64> K={0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};
std::uint32_t rotr(std::uint32_t x,int n){return(x>>n)|(x<<(32-n));}
}
ExperimentManifest make_live_campaign_manifest(const LiveCampaignSpec&s,const std::vector<agents::ModelIdentity>&models){ExperimentManifest m;m.implementation_revision=s.implementation_revision; const char* eh=std::getenv("COAGENTICS_EXPECTATIONS_SHA256"); const char* ep=std::getenv("COAGENTICS_EXPECTATIONS_PATH"); if(eh&&*eh)m.research_expectations_sha256=eh; if(ep&&*ep)m.research_expectations_path=ep; const char* ej=std::getenv("COAGENTICS_EXPECTATIONS_JSON"); if(ej&&*ej)m.research_expectations_json=ej; const char* pd=std::getenv("COAGENTICS_POPULATION_DESIGN"); if(pd&&*pd)m.population_design=pd; const char* ad=std::getenv("COAGENTICS_ACTIVATION_DESIGN"); if(ad&&*ad)m.activation_design=ad;m.created_from_seed=s.base_seed;m.models=models;for(size_t i=0;i<s.n_seeds;++i)m.seeds.push_back(s.base_seed+i);m.model_visible_fields={"market.time","market.asset","market.fundamental","market.public_signal","market.best_bid","market.best_ask","market.last_trade","agent.role","agent.cash","agent.inventory","agent.private_value_or_cost","agent.remaining_demand","agent.realized_payoff","information.action_constraints"};m.audit_only_fields={"experiment_id","run_id","request_id","provider","model_identity","experiment_seed","inference_seed","treatment_label","implementation_revision","manifest_hash"};m.hypotheses={};m.metrics={"parse_success","action_validity","non_hold_action_rate","market_acceptance_rate","execution_observed","allocative_efficiency","surplus","trade_count","mean_trade_price","behavioral_fingerprint"};m.acceptance_rules={"Layer A: allocative efficiency >90% in every preregistered trial for each mechanism","Live provenance rate >= "+std::to_string(s.min_provenance_rate),"Interface success rate >= "+std::to_string(s.min_interface_rate),"Non-HOLD market action rate >= "+std::to_string(s.min_market_action_rate),"Accepted/non-HOLD action rate >= "+std::to_string(s.min_market_acceptance_rate),"At least "+std::to_string(s.min_models)+" distinct live model identities for local PoC readiness"};m.claim_boundary="Phase I black-box behavioral measurement only. No Phase II construct validation, classifier-accuracy claim, or commercial multi-provider claim.";return m;}
std::string experiment_manifest_canonical_json(const ExperimentManifest&m){std::ostringstream o;o<<std::fixed<<std::setprecision(6);o<<"{"<<"\"schema_version\":\""<<esc(m.schema_version)<<"\",\"experiment_id\":\""<<esc(m.experiment_id)<<"\",\"implementation_revision\":\""<<esc(m.implementation_revision)<<"\",\"base_seed\":"<<m.created_from_seed<<",\"mechanism\":\""<<esc(m.mechanism)<<"\",\"population_design\":\""<<esc(m.population_design)<<"\",\"activation_design\":\""<<esc(m.activation_design)<<"\",\"models\":[";for(size_t i=0;i<m.models.size();++i){if(i)o<<",";auto&x=m.models[i];o<<"{\"provider\":\""<<esc(x.provider)<<"\",\"model\":\""<<esc(x.model)<<"\",\"version\":\""<<esc(x.version)<<"\",\"endpoint_class\":\""<<esc(x.endpoint_class)<<"\"}";}o<<"],\"seeds\":[";for(size_t i=0;i<m.seeds.size();++i){if(i)o<<",";o<<m.seeds[i];}o<<"],\"treatments\":";strings(o,m.treatments);o<<",\"information_boundary\":{\"model_visible\":";strings(o,m.model_visible_fields);o<<",\"audit_only\":";strings(o,m.audit_only_fields);o<<"},\"inference\":{\"temperature\":"<<m.temperature<<",\"seed_requested\":"<<(m.inference_seed_requested?"true":"false")<<"},\"hypotheses\":";strings(o,m.hypotheses);o<<",\"metrics\":";strings(o,m.metrics);o<<",\"acceptance_rules\":";strings(o,m.acceptance_rules);o<<",\"claim_boundary\":\""<<esc(m.claim_boundary)<<"\",\"research_expectations\":{\"sha256\":\""<<esc(m.research_expectations_sha256)<<"\",\"path\":\""<<esc(m.research_expectations_path)<<"\",\"document\":"<<(m.research_expectations_json.empty()?"null":m.research_expectations_json)<<"}}";return o.str();}
std::string sha256_hex(const std::string&input){std::vector<unsigned char>d(input.begin(),input.end());std::uint64_t bits=(std::uint64_t)d.size()*8;d.push_back(0x80);while(d.size()%64!=56)d.push_back(0);for(int i=7;i>=0;--i)d.push_back((bits>>(i*8))&0xff);std::array<std::uint32_t,8>h={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};for(size_t off=0;off<d.size();off+=64){std::uint32_t w[64];for(int i=0;i<16;++i)w[i]=(d[off+4*i]<<24)|(d[off+4*i+1]<<16)|(d[off+4*i+2]<<8)|d[off+4*i+3];for(int i=16;i<64;++i){auto s0=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>3);auto s1=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>10);w[i]=w[i-16]+s0+w[i-7]+s1;}auto a=h[0],b=h[1],c=h[2],dd=h[3],e=h[4],f=h[5],g=h[6],hh=h[7];for(int i=0;i<64;++i){auto S1=rotr(e,6)^rotr(e,11)^rotr(e,25);auto ch=(e&f)^((~e)&g);auto t1=hh+S1+ch+K[i]+w[i];auto S0=rotr(a,2)^rotr(a,13)^rotr(a,22);auto maj=(a&b)^(a&c)^(b&c);auto t2=S0+maj;hh=g;g=f;f=e;e=dd+t1;dd=c;c=b;b=a;a=t1+t2;}h[0]+=a;h[1]+=b;h[2]+=c;h[3]+=dd;h[4]+=e;h[5]+=f;h[6]+=g;h[7]+=hh;}std::ostringstream o;for(auto x:h)o<<std::hex<<std::setw(8)<<std::setfill('0')<<x;return o.str();}
std::string experiment_manifest_hash(const ExperimentManifest&m){return sha256_hex(experiment_manifest_canonical_json(m));}
void write_frozen_manifest(const ExperimentManifest&m,const std::string&path){std::filesystem::create_directories(std::filesystem::path(path).parent_path());auto json=experiment_manifest_canonical_json(m);auto hash=sha256_hex(json);std::ofstream f(path,std::ios::trunc);if(!f)throw std::runtime_error("cannot write preregistration manifest: "+path);f<<"{\n  \"manifest_sha256\": \""<<hash<<"\",\n  \"frozen_before_observation\": true,\n  \"manifest\": "<<json<<"\n}\n";}
}
